image: docker

workflow:
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
      when: always
    - if: $CI_COMMIT_BRANCH == "staging"
      when: always

stages:
  - build
  - staging
  - deploy

variables:
  TAG_COMMIT: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG

build-letsmetrix-frontend:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: ['']
  script:
    - echo $CI_REGISTRY_USER
    - echo $CI_REGISTRY_PASSWORD
    - mkdir -p /kaniko/.docker
    - >-
      /kaniko/executor
      --context .
      --dockerfile /Dockerfile
      --destination ${TAG_COMMIT}
    - echo "Compile complete."

staging-letsmetrix-frontend:
  stage: staging
  rules:
    - if: $CI_COMMIT_BRANCH == "staging"
  services:
    - docker:dind
  tags:
    - staging
  script:
    - echo "Deploy to staging environment"
    - echo "get variables $RSA_KEY $SERVER_IP"
    - 'command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client wget gnupg -y )'
    - eval $(ssh-agent -s)
    - echo "$RSA_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - touch ~/.ssh/config
    - touch ~/.ssh/known_hosts
    - chmod -R 400 ~/.ssh
    - ssh-keyscan $SERVER_IP >> ~/.ssh/known_hosts
    - '[[ -f /.dockerinit ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER $CI_REGISTRY --password-stdin;
    - docker pull $TAG_COMMIT;
    - docker save -o ./letsmetrix-frontend-staging.tar $TAG_COMMIT;
    - scp -r ./letsmetrix-frontend-staging.tar $SERVER_USER@$SERVER_IP:./
    - ssh $SERVER_USER@$SERVER_IP "docker load -i ./letsmetrix-frontend-staging.tar"
    - ssh $SERVER_USER@$SERVER_IP "rm -rf ./letsmetrix-frontend-staging.tar"
    - ssh $SERVER_USER@$SERVER_IP "docker container rm -v -f letsmetrix-frontend-staging || true"
    - ssh $SERVER_USER@$SERVER_IP "docker system prune -f"
    - ssh $SERVER_USER@$SERVER_IP "docker run -d -p 7009:3000 --name letsmetrix-frontend-staging --restart always $TAG_COMMIT"

deploy-letsmetrix-frontend:
  stage: deploy
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
  services:
    - docker:dind
  tags:
    - deployment
  script:
    - echo "get variables $RSA_KEY $SERVER_IP"
    - 'command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client wget gnupg -y )'
    - eval $(ssh-agent -s)
    - echo "$RSA_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - touch ~/.ssh/config
    - touch ~/.ssh/known_hosts
    - chmod -R 400 ~/.ssh
    - ssh-keyscan $SERVER_IP >> ~/.ssh/known_hosts
    - '[[ -f /.dockerinit ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER $CI_REGISTRY --password-stdin;
    - docker pull $TAG_COMMIT;
    - docker save -o ./letsmetrix-frontend.tar $TAG_COMMIT;
    - scp -r ./letsmetrix-frontend.tar $SERVER_USER@$SERVER_IP:./
    - ssh $SERVER_USER@$SERVER_IP "docker load -i ./letsmetrix-frontend.tar"
    - ssh $SERVER_USER@$SERVER_IP "rm -rf ./letsmetrix-frontend.tar"
    - ssh $SERVER_USER@$SERVER_IP "docker container rm -v -f letsmetrix-frontend || true"
    - ssh $SERVER_USER@$SERVER_IP "docker system prune -f"
    - ssh $SERVER_USER@$SERVER_IP "docker run -d -p 7006:3000 --name letsmetrix-frontend --restart always $TAG_COMMIT"
